PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "coin" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "short_name" VARCHAR(255) NOT NULL, "url" TEXT NOT NULL, "price" VARCHAR(255) NOT NULL);
INSERT INTO coin VALUES(1,'Bitcoin','BTC','https://coinmarketcap.com/currencies/bitcoin/','57756.26');
INSERT INTO coin VALUES(2,'Ethereum','ETH','https://coinmarketcap.com/currencies/ethereum/','3785.75');
INSERT INTO coin VALUES(3,'Binance Coin','BNB','https://coinmarketcap.com/currencies/binance-coin/','469.05');
INSERT INTO coin VALUES(4,'Cardano','ADA','https://coinmarketcap.com/currencies/cardano/','43132');
INSERT INTO coin VALUES(5,'Tether','USDT','https://coinmarketcap.com/currencies/tether/','1.00');
INSERT INTO coin VALUES(6,'XRP','XRP','https://coinmarketcap.com/currencies/xrp/','41275');
INSERT INTO coin VALUES(7,'Solana','SOL','https://coinmarketcap.com/currencies/solana/','149.90');
INSERT INTO coin VALUES(8,'Polkadot','DOT','https://coinmarketcap.com/currencies/polkadot-new/','39.93');
INSERT INTO coin VALUES(9,'USD Coin','USDC','https://coinmarketcap.com/currencies/usd-coin/','0.9998');
INSERT INTO coin VALUES(10,'Dogecoin','DOGE','https://coinmarketcap.com/currencies/dogecoin/','0.2344');
INSERT INTO coin VALUES(11,'Uniswap','UNI','https://coinmarketcap.com/currencies/uniswap/','44434');
INSERT INTO coin VALUES(12,'Terra','LUNA','https://coinmarketcap.com/currencies/terra-luna/','37.33');
INSERT INTO coin VALUES(13,'Binance USD','BUSD','https://coinmarketcap.com/currencies/binance-usd/','1.00');
INSERT INTO coin VALUES(14,'Litecoin','LTC','https://coinmarketcap.com/currencies/litecoin/','181.06');
INSERT INTO coin VALUES(15,'Avalanche','AVAX','https://coinmarketcap.com/currencies/avalanche/','56.13');
INSERT INTO coin VALUES(16,'Chainlink','LINK','https://coinmarketcap.com/currencies/chainlink/','27.00');
INSERT INTO coin VALUES(17,'Wrapped Bitcoin','WBTC','https://coinmarketcap.com/currencies/wrapped-bitcoin/','57640.73');
INSERT INTO coin VALUES(18,'Bitcoin Cash','BCH','https://coinmarketcap.com/currencies/bitcoin-cash/','596.36');
INSERT INTO coin VALUES(19,'Algorand','ALGO','https://coinmarketcap.com/currencies/algorand/','29221');
INSERT INTO coin VALUES(20,'SHIBA INU','SHIB','https://coinmarketcap.com/currencies/shiba-inu/','0.00');
INSERT INTO coin VALUES(21,'Stellar','XLM','https://coinmarketcap.com/currencies/stellar/','0.37');
INSERT INTO coin VALUES(22,'Axie Infinity','AXS','https://coinmarketcap.com/currencies/axie-infinity/','138.64');
INSERT INTO coin VALUES(23,'Polygon','MATIC','https://coinmarketcap.com/currencies/polygon/','45658');
INSERT INTO coin VALUES(24,'Filecoin','FIL','https://coinmarketcap.com/currencies/filecoin/','70.85');
INSERT INTO coin VALUES(25,'VeChain','VET','https://coinmarketcap.com/currencies/vechain/','0.12');
INSERT INTO coin VALUES(26,'Cosmos','ATOM','https://coinmarketcap.com/currencies/cosmos/','33.96');
INSERT INTO coin VALUES(27,'Internet Computer','ICP','https://coinmarketcap.com/currencies/internet-computer/','42.83');
INSERT INTO coin VALUES(28,'Ethereum Classic','ETC','https://coinmarketcap.com/currencies/ethereum-classic/','54.43');
INSERT INTO coin VALUES(29,'TRON','TRX','https://coinmarketcap.com/currencies/tron/','0.10');
INSERT INTO coin VALUES(30,'FTX Token','FTT','https://coinmarketcap.com/currencies/ftx-token/','55.18');
INSERT INTO coin VALUES(31,'Dai','DAI','https://coinmarketcap.com/currencies/multi-collateral-dai/','1.00');
INSERT INTO coin VALUES(32,'Tezos','XTZ','https://coinmarketcap.com/currencies/tezos/','41821');
INSERT INTO coin VALUES(33,'THETA','THETA','https://coinmarketcap.com/currencies/theta/','44445');
INSERT INTO coin VALUES(34,'Bitcoin BEP2','BTCB','https://coinmarketcap.com/currencies/bitcoin-bep2/','57687.23');
INSERT INTO coin VALUES(35,'Hedera','HBAR','https://coinmarketcap.com/currencies/hedera/','0.38');
INSERT INTO coin VALUES(36,'Fantom','FTM','https://coinmarketcap.com/currencies/fantom/','44379');
INSERT INTO coin VALUES(37,'Monero','XMR','https://coinmarketcap.com/currencies/monero/','267.75');
INSERT INTO coin VALUES(38,'Crypto.com Coin','CRO','https://coinmarketcap.com/currencies/crypto-com-coin/','0.19');
INSERT INTO coin VALUES(39,'Elrond','EGLD','https://coinmarketcap.com/currencies/elrond-egld/','243.39');
INSERT INTO coin VALUES(40,'PancakeSwap','CAKE','https://coinmarketcap.com/currencies/pancakeswap/','19.90');
INSERT INTO coin VALUES(41,'EOS','EOS','https://coinmarketcap.com/currencies/eos/','23833');
INSERT INTO coin VALUES(42,'eCash','XEC','https://coinmarketcap.com/currencies/ecash/','0.00');
INSERT INTO coin VALUES(43,'Klaytn','KLAY','https://coinmarketcap.com/currencies/klaytn/','22647');
INSERT INTO coin VALUES(44,'NEAR Protocol','NEAR','https://coinmarketcap.com/currencies/near-protocol/','30498');
INSERT INTO coin VALUES(45,'Aave','AAVE','https://coinmarketcap.com/currencies/aave/','303.84');
INSERT INTO coin VALUES(46,'IOTA','MIOTA','https://coinmarketcap.com/currencies/iota/','12785');
INSERT INTO coin VALUES(47,'Quant','QNT','https://coinmarketcap.com/currencies/quant/','292.13');
INSERT INTO coin VALUES(48,'Waves','WAVES','https://coinmarketcap.com/currencies/waves/','32.26');
INSERT INTO coin VALUES(49,'The Graph','GRT','https://coinmarketcap.com/currencies/the-graph/','0.72');
INSERT INTO coin VALUES(50,'Bitcoin SV','BSV','https://coinmarketcap.com/currencies/bitcoin-sv/','171.56');
INSERT INTO coin VALUES(51,'Neo','NEO','https://coinmarketcap.com/currencies/neo/','44.88');
INSERT INTO coin VALUES(52,'Kusama','KSM','https://coinmarketcap.com/currencies/kusama/','351.72');
INSERT INTO coin VALUES(53,'Stacks','STX','https://coinmarketcap.com/currencies/stacks/','42401');
INSERT INTO coin VALUES(54,'TerraUSD','UST','https://coinmarketcap.com/currencies/terrausd/','1.00');
INSERT INTO coin VALUES(55,'UNUS SED LEO','LEO','https://coinmarketcap.com/currencies/unus-sed-leo/','25600');
INSERT INTO coin VALUES(56,'Maker','MKR','https://coinmarketcap.com/currencies/maker/','2535.39');
INSERT INTO coin VALUES(57,'BitTorrent','BTT','https://coinmarketcap.com/currencies/bittorrent/','0.00');
INSERT INTO coin VALUES(58,'Harmony','ONE','https://coinmarketcap.com/currencies/harmony/','0.22');
INSERT INTO coin VALUES(59,'OMG Network','OMG','https://coinmarketcap.com/currencies/omg/','14.35');
INSERT INTO coin VALUES(60,'Helium','HNT','https://coinmarketcap.com/currencies/helium/','19.87');
INSERT INTO coin VALUES(61,'Chiliz','CHZ','https://coinmarketcap.com/currencies/chiliz/','0.33');
INSERT INTO coin VALUES(62,'Amp','AMP','https://coinmarketcap.com/currencies/amp/','0.05');
INSERT INTO coin VALUES(63,'Dash','DASH','https://coinmarketcap.com/currencies/dash/','185.76');
INSERT INTO coin VALUES(64,'Celo','CELO','https://coinmarketcap.com/currencies/celo/','29342');
INSERT INTO coin VALUES(65,'Arweave','AR','https://coinmarketcap.com/currencies/arweave/','52.71');
INSERT INTO coin VALUES(66,'Compound','COMP','https://coinmarketcap.com/currencies/compound/','313.88');
INSERT INTO coin VALUES(67,'THORChain','RUNE','https://coinmarketcap.com/currencies/thorchain/','21732');
INSERT INTO coin VALUES(68,'Revain','REV','https://coinmarketcap.com/currencies/revain/','0.02');
INSERT INTO coin VALUES(69,'Decred','DCR','https://coinmarketcap.com/currencies/decred/','124.12');
INSERT INTO coin VALUES(70,'Holo','HOT','https://coinmarketcap.com/currencies/holo/','0.01');
INSERT INTO coin VALUES(71,'NEM','XEM','https://coinmarketcap.com/currencies/nem/','0.18');
INSERT INTO coin VALUES(72,'Zcash','ZEC','https://coinmarketcap.com/currencies/zcash/','120.91');
INSERT INTO coin VALUES(73,'Theta Fuel','TFUEL','https://coinmarketcap.com/currencies/theta-fuel/','0.29');
INSERT INTO coin VALUES(74,'XDC Network','XDC','https://coinmarketcap.com/currencies/xinfin/','0.12');
INSERT INTO coin VALUES(75,'Decentraland','MANA','https://coinmarketcap.com/currencies/decentraland/','0.77');
INSERT INTO coin VALUES(76,'ICON','ICX','https://coinmarketcap.com/currencies/icon/','44410');
INSERT INTO coin VALUES(77,'Celsius','CEL','https://coinmarketcap.com/currencies/celsius/','25324');
INSERT INTO coin VALUES(78,'Enjin Coin','ENJ','https://coinmarketcap.com/currencies/enjin-coin/','22282');
INSERT INTO coin VALUES(79,'SushiSwap','SUSHI','https://coinmarketcap.com/currencies/sushiswap/','20363');
INSERT INTO coin VALUES(80,'Qtum','QTUM','https://coinmarketcap.com/currencies/qtum/','13.21');
INSERT INTO coin VALUES(81,'yearn.finance','YFI','https://coinmarketcap.com/currencies/yearn-finance/','35286.75');
INSERT INTO coin VALUES(82,'TrueUSD','TUSD','https://coinmarketcap.com/currencies/trueusd/','1.00');
INSERT INTO coin VALUES(83,'dYdX','DYDX','https://coinmarketcap.com/currencies/dydx/','22.66');
INSERT INTO coin VALUES(84,'Curve DAO Token','CRV','https://coinmarketcap.com/currencies/curve-dao-token/','33635');
INSERT INTO coin VALUES(85,'Huobi Token','HT','https://coinmarketcap.com/currencies/huobi-token/','19541');
INSERT INTO coin VALUES(86,'Bitcoin Gold','BTG','https://coinmarketcap.com/currencies/bitcoin-gold/','69.61');
INSERT INTO coin VALUES(87,'Perpetual Protocol','PERP','https://coinmarketcap.com/currencies/perpetual-protocol/','17.64');
INSERT INTO coin VALUES(88,'Flow','FLOW','https://coinmarketcap.com/currencies/flow/','18.81');
INSERT INTO coin VALUES(89,'Telcoin','TEL','https://coinmarketcap.com/currencies/telcoin/','0.02');
INSERT INTO coin VALUES(90,'Zilliqa','ZIL','https://coinmarketcap.com/currencies/zilliqa/','0.10');
INSERT INTO coin VALUES(91,'Mina','MINA','https://coinmarketcap.com/currencies/mina/','13606');
INSERT INTO coin VALUES(92,'Synthetix','SNX','https://coinmarketcap.com/currencies/synthetix-network-token/','28004');
INSERT INTO coin VALUES(93,'Ravencoin','RVN','https://coinmarketcap.com/currencies/ravencoin/','0.11');
INSERT INTO coin VALUES(94,'Basic Attention Token','BAT','https://coinmarketcap.com/currencies/basic-attention-token/','0.70');
INSERT INTO coin VALUES(95,'Serum','SRM','https://coinmarketcap.com/currencies/serum/','22828');
INSERT INTO coin VALUES(96,'Ren','REN','https://coinmarketcap.com/currencies/ren/','44197');
INSERT INTO coin VALUES(97,'IOST','IOST','https://coinmarketcap.com/currencies/iostoken/','0.05');
INSERT INTO coin VALUES(98,'OKB','OKB','https://coinmarketcap.com/currencies/okb/','16.37');
INSERT INTO coin VALUES(99,'renBTC','RENBTC','https://coinmarketcap.com/currencies/renbtc/','57530.32');
INSERT INTO coin VALUES(100,'Mdex','MDX','https://coinmarketcap.com/currencies/mdex/','13516');
COMMIT;
